export const personalityQuestions = [
  {
    id: 1,
    name: "strengths",
    type: "textarea",
    label: "What are your biggest strengths?",
    placeholder: "E.g. I'm good at explaining things, staying organized, and helping others.",
    maxLength: 300,
    required: true,
  },
  {
    id: 2,
    name: "weaknesses",
    type: "textarea",
    label: "What are some areas you'd like to improve?",
    placeholder: "E.g. I sometimes procrastinate or struggle with public speaking.",
    maxLength: 300,
    required: true,
  },
  {
    id: 3,
    name: "hobbies",
    type: "textarea",
    label: "What do you enjoy doing in your free time?",
    placeholder: "E.g. Gaming, reading, soccer, coding, drawing.",
    maxLength: 300,
    required: true,
  },
  {
    id: 4,
    name: "enjoyedSubjects",
    type: "textarea",
    label: "Which school subjects do you enjoy the most?",
    placeholder: "E.g. Mathematics, Life Sciences, Geography.",
    maxLength: 300,
    required: true,
  },
  {
    id: 5,
    name: "dislikedSubjects",
    type: "textarea",
    label: "Which subjects do you enjoy the least?",
    placeholder: "E.g. Accounting, Physical Sciences.",
    maxLength: 300,
    required: true,
  },
  {
    id: 6,
    name: "dreamJob",
    type: "textarea",
    label: "What is your dream job?",
    placeholder: "E.g. Software Engineer, Doctor, Architect.",
    maxLength: 300,
    required: true,
  },
  {
    id: 7,
    name: "goals",
    type: "textarea",
    label: "What are your career goals?",
    placeholder: "E.g. I want to build my own tech company.",
    maxLength: 300,
    required: true,
  },
  {
    id: 8,
    name: "aspiration",
    type: "textarea",
    label: "What do you aspire to achieve in life?",
    placeholder: "E.g. Financial freedom and meaningful work.",
    maxLength: 300,
    required: true,
  },
  {
    id: 9,
    name: "preferredEnvironment",
    type: "select",
    label: "What learning environment suits you best?",
    required: true,
    options: [
      { value: "practical", label: "Practical / hands-on" },
      { value: "theory", label: "Theory-focused" },
      { value: "balanced", label: "Balanced" },
      { value: "self-paced", label: "Self-paced / independent" },
      { value: "group", label: "Group / team-based" },
    ],
  },
  {
    id: 10,
    name: "workStyle",
    type: "select",
    label: "How do you prefer to work?",
    required: true,
    options: [
      { value: "independent", label: "Independent / solo work" },
      { value: "collaborative", label: "Collaborative / team work" },
      { value: "flexible", label: "Flexible / both" },
    ],
  },
  {
    id: 11,
    name: "problemSolvingApproach",
    type: "select",
    label: "How do you usually solve problems?",
    required: true,
    options: [
      { value: "creative", label: "Creative / innovative" },
      { value: "analytical", label: "Analytical / logical" },
      { value: "balanced", label: "Balanced approach" },
    ],
  },
];