import { studentSubjectsData } from "../../Utils/subjects";

export const personalityQuestions = [
  {
    id: 1,
    name: "strengths",
    type: "multiple",
    label: "What are your biggest strengths?",
    helperText: "Choose exactly 3 strengths.",
    required: true,
    minAnswers: 3,
    maxAnswers: 3,
    options: [
      "Leadership",
      "Creativity",
      "Problem Solving",
      "Communication",
      "Teamwork",
      "Critical Thinking",
      "Adaptability",
      "Organisation",
      "Time Management",
      "Attention to Detail",
      "Confidence",
      "Empathy",
      "Curiosity",
      "Resilience",
      "Decision Making",
      "Fast Learner",
      "Planning",
      "Self Discipline",
    ],
  },
  {
    id: 2,
    name: "weaknesses",
    type: "multiple",
    label: "Which areas would you like to improve?",
    helperText: "Choose exactly 3 areas.",
    required: true,
    minAnswers: 3,
    maxAnswers: 3,
    options: [
      "Public Speaking",
      "Time Management",
      "Procrastination",
      "Overthinking",
      "Confidence",
      "Stress Management",
      "Delegating",
      "Impatience",
      "Perfectionism",
      "Asking for Help",
      "Organisation",
      "Focus",
      "Decision Making",
      "Taking Criticism",
      "Multitasking",
    ],
  },
  {
    id: 3,
    name: "hobbies",
    type: "multiple",
    label: "What do you enjoy doing in your free time?",
    helperText: "Choose between 3 and 5 hobbies.",
    required: true,
    minAnswers: 3,
    maxAnswers: 5,
    options: [
      "Gaming",
      "Reading",
      "Coding",
      "Drawing",
      "Painting",
      "Music",
      "Singing",
      "Dancing",
      "Cooking",
      "Photography",
      "Writing",
      "Watching Movies",
      "Watching Sports",
      "Gym",
      "Running",
      "Hiking",
      "Travelling",
      "Chess",
      "Volunteering",
      "Entrepreneurship",
      "Content Creation",
      "Fashion",
      "Gardening",
      "DIY Projects",
    ],
  },
  {
    id: 4,
    name: "enjoyedSubjects",
    type: "subjects",
    label: "Which subjects do you enjoy the most?",
    helperText: "Choose exactly 3 subjects.",
    required: true,
    minAnswers: 3,
    maxAnswers: 3,
    options: studentSubjectsData,
  },
  {
    id: 5,
    name: "dislikedSubjects",
    type: "subjects",
    label: "Which subjects do you enjoy the least?",
    helperText: "Choose between 1 and 3 subjects.",
    required: true,
    minAnswers: 1,
    maxAnswers: 3,
    options: studentSubjectsData,
  },
  {
    id: 6,
    name: "dreamJob",
    type: "single",
    label: "What is your dream job?",
    helperText: "Choose one option.",
    required: true,
    minAnswers: 1,
    maxAnswers: 1,
    options: [
      { label: "Software Engineer", value: "Software Engineer" },
      { label: "Doctor", value: "Doctor" },
      { label: "Lawyer", value: "Lawyer" },
      { label: "Teacher", value: "Teacher" },
      { label: "Accountant", value: "Accountant" },
      { label: "Architect", value: "Architect" },
      { label: "Mechanical Engineer", value: "Mechanical Engineer" },
      { label: "Electrical Engineer", value: "Electrical Engineer" },
      { label: "Civil Engineer", value: "Civil Engineer" },
      { label: "Pilot", value: "Pilot" },
      { label: "Nurse", value: "Nurse" },
      { label: "Pharmacist", value: "Pharmacist" },
      { label: "Psychologist", value: "Psychologist" },
      { label: "Data Scientist", value: "Data Scientist" },
      { label: "Cybersecurity Specialist", value: "Cybersecurity Specialist" },
      { label: "Graphic Designer", value: "Graphic Designer" },
      { label: "UX/UI Designer", value: "UX/UI Designer" },
      { label: "Marketing Specialist", value: "Marketing Specialist" },
      { label: "Business Analyst", value: "Business Analyst" },
      { label: "Entrepreneur", value: "Entrepreneur" },
      { label: "Police Officer", value: "Police Officer" },
      { label: "Social Worker", value: "Social Worker" },
      { label: "Chef", value: "Chef" },
      { label: "Journalist", value: "Journalist" },
    ],
  },
  {
    id: 7,
    name: "goals",
    type: "single",
    label: "What is your primary career goal?",
    helperText: "Choose one option.",
    required: true,
    minAnswers: 1,
    maxAnswers: 1,
    options: [
      { label: "Help People", value: "Help People" },
      { label: "Earn a High Income", value: "Earn a High Income" },
      { label: "Become an Expert", value: "Become an Expert" },
      { label: "Start My Own Business", value: "Start My Own Business" },
      { label: "Lead a Company", value: "Lead a Company" },
      {
        label: "Solve Real-world Problems",
        value: "Solve Real-world Problems",
      },
      { label: "Work with Technology", value: "Work with Technology" },
      { label: "Travel the World", value: "Travel the World" },
      {
        label: "Achieve Work-life Balance",
        value: "Achieve Work-life Balance",
      },
      {
        label: "Create Innovative Products",
        value: "Create Innovative Products",
      },
      { label: "Job Security", value: "Job Security" },
      { label: "Continuous Learning", value: "Continuous Learning" },
    ],
  },
  {
    id: 8,
    name: "aspiration",
    type: "single",
    label: "What do you aspire to achieve in life?",
    helperText: "Choose one option.",
    required: true,
    minAnswers: 1,
    maxAnswers: 1,
    options: [
      { label: "Financial Freedom", value: "Financial Freedom" },
      { label: "Support My Family", value: "Support My Family" },
      { label: "Own a Business", value: "Own a Business" },
      { label: "Become a Leader", value: "Become a Leader" },
      { label: "Make a Difference", value: "Make a Difference" },
      { label: "Travel the World", value: "Travel the World" },
      { label: "Leave a Legacy", value: "Leave a Legacy" },
      {
        label: "Become an Industry Expert",
        value: "Become an Industry Expert",
      },
      {
        label: "Build Innovative Technology",
        value: "Build Innovative Technology",
      },
      { label: "Improve My Community", value: "Improve My Community" },
      { label: "Personal Growth", value: "Personal Growth" },
      { label: "Lifelong Learning", value: "Lifelong Learning" },
    ],
  },
  {
    id: 9,
    name: "preferredEnvironment",
    type: "single",
    label: "What learning environment suits you best?",
    helperText: "Choose one option.",
    required: true,
    minAnswers: 1,
    maxAnswers: 1,
    options: [
      { label: "Practical / Hands-on", value: "practical" },
      { label: "Theory-focused", value: "theory" },
      { label: "Balanced", value: "balanced" },
      { label: "Self-paced / Independent", value: "self-paced" },
      { label: "Group / Team-based", value: "group" },
    ],
  },
  {
    id: 10,
    name: "workStyle",
    type: "single",
    label: "How do you prefer to work?",
    helperText: "Choose one option.",
    required: true,
    minAnswers: 1,
    maxAnswers: 1,
    options: [
      { label: "Independent / Solo Work", value: "independent" },
      { label: "Collaborative / Team Work", value: "collaborative" },
      { label: "Flexible / Both", value: "flexible" },
    ],
  },
  {
    id: 11,
    name: "problemSolvingApproach",
    type: "single",
    label: "How do you usually solve problems?",
    helperText: "Choose one option.",
    required: true,
    minAnswers: 1,
    maxAnswers: 1,
    options: [
      { label: "Creative / Innovative", value: "creative" },
      { label: "Analytical / Logical", value: "analytical" },
      { label: "Practical", value: "practical" },
      { label: "Research-based", value: "research" },
      { label: "Collaborative", value: "collaborative" },
      { label: "Balanced", value: "balanced" },
    ],
  },
];

export const STEPS = [
  { questions: [personalityQuestions[0]] },
  { questions: [personalityQuestions[1]] },
  { questions: [personalityQuestions[2]] },
  {
    questions: [personalityQuestions[3], personalityQuestions[4]],
    paired: true,
  },
  { questions: [personalityQuestions[5]] },
  { questions: [personalityQuestions[6]] },
  { questions: [personalityQuestions[7]] },
  { questions: [personalityQuestions[8]] },
  { questions: [personalityQuestions[9]] },
  { questions: [personalityQuestions[10]] },
];
