//subjects for admin
export const adminSubjectsData = [
  "Accounting",
  "Afrikaans",
  "Agricultural Management Practices",
  "Agricultural Sciences",
  "Agricultural Technology",
  "Business Studies",
  "Civil Technology",
  "Computer Applications Technology",
  "Consumer Studies",
  "Dance Studies",
  "Design",
  "Dramatic Arts",
  "Economics",
  "Electrical Technology",
  "Engineering Graphics & Design",
  "English",
  "Geography",
  "History",
  "Hospitality Studies",
  "Information Technology",
  "Life Orientation",
  "Life Sciences",
  "Mathematical Literacy",
  "Mathematics",
  "Mechanical Technology",
  "Music",
  "Ndebele",
  "Northern Sotho",
  "Physical Sciences",
  "Religion Studies",
  "Southern Sotho",
  "Swazi",
  "Tourism",
  "Tsonga",
  "Tswana",
  "Venda",
  "Visual Arts",
  "Xhosa",
  "iSiZulu",
];

//subjects from logged in student
export const studentSubjectsData = [
  "Accounting",
  "Afrikaans FAL",
  "Afrikaans HL",
  "Agricultural Management Practices",
  "Agricultural Sciences",
  "Agricultural Technology",
  "Business Studies",
  "Civil Technology",
  "Computer Applications Technology",
  "Consumer Studies",
  "Dance Studies",
  "Design",
  "Dramatic Arts",
  "Economics",
  "Electrical Technology",
  "Engineering Graphics & Design",
  "English FAL",
  "English HL",
  "Geography",
  "History",
  "Hospitality Studies",
  "Information Technology",
  "Life Orientation",
  "Life Sciences",
  "Mathematical Literacy",
  "Mathematics",
  "Mechanical Technology",
  "Music",
  "Ndebele HL",
  "Northern Sotho HL",
  "Physical Science",
  "Religion Studies",
  "Southern Sotho HL",
  "Swazi HL",
  "Technical Mathematics",
  "Tourism",
  "Tsonga HL",
  "Tswana HL",
  "Venda HL",
  "Visual Arts",
  "Xhosa HL",
  "iSiZulu HL",
];

/*Used for guests */
export const SUBJECT_CATEGORIES = {
  MATHEMATICS: [
    "Mathematics",
    "Mathematical Literacy",
    "Technical Mathematics",
  ],

  LIFE_ORIENTATION: [
    "Life Orientation",
  ],

  HOME_LANGUAGES: [
    "Afrikaans HL",
    "English HL",
    "Ndebele HL",
    "Northern Sotho HL",
    "Southern Sotho HL",
    "Swazi HL",
    "Tsonga HL",
    "Tswana HL",
    "Venda HL",
    "Xhosa HL",
    "iSiZulu HL",
  ],

  FIRST_ADDITIONAL_LANGUAGES: [
    "Afrikaans FAL",
    "English FAL",
  ],

  ELECTIVES: [
    "Accounting",
    "Agricultural Management Practices",
    "Agricultural Sciences",
    "Agricultural Technology",
    "Business Studies",
    "Civil Technology",
    "Computer Applications Technology",
    "Consumer Studies",
    "Dance Studies",
    "Design",
    "Dramatic Arts",
    "Economics",
    "Electrical Technology",
    "Engineering Graphics & Design",
    "Geography",
    "History",
    "Hospitality Studies",
    "Information Technology",
    "Life Sciences",
    "Mechanical Technology",
    "Music",
    "Physical Science",
    "Religion Studies",
    "Tourism",
    "Visual Arts",
  ],
};


export const SUBJECT_RULES = {
  MATHEMATICS: { min: 1, max: 1 },
  LIFE_ORIENTATION: { min: 1, max: 1 },
  HOME_LANGUAGES: { min: 1 },
  FIRST_ADDITIONAL_LANGUAGES: { min: 1 },
  ELECTIVES: { min: 3 },
};