//subjects for admin
export const adminSubjectsData = [
  "Accounting",
  "Afrikaans",
  "Agricultural Management Practices",
  "Agricultural Sciences",
  "Agricultural Technology",
  "Business Studies",
  "Civil Technology",
  "Computer Applications Technology",
  "Consumer Studies",
  "Dance Studies",
  "Design",
  "Dramatic Arts",
  "Economics",
  "Electrical Technology",
  "Engineering Graphics & Design",
  "English",
  "Geography",
  "History",
  "Hospitality Studies",
  "Information Technology",
  "Life Orientation",
  "Life Sciences",
  "Mathematical Literacy",
  "Mathematics",
  "Mechanical Technology",
  "Music",
  "Ndebele",
  "Northern Sotho",
  "Physical Sciences",
  "Religion Studies",
  "Southern Sotho",
  "Swazi",
  "Tourism",
  "Tsonga",
  "Tswana",
  "Venda",
  "Visual Arts",
  "Xhosa",
  "iSiZulu",
];

//subjects from student
export const studentSubjectsData = [
  "Accounting",
  "Afrikaans FAL",
  "Afrikaans HL",
  "Agricultural Management Practices",
  "Agricultural Sciences",
  "Agricultural Technology",
  "Business Studies",
  "Civil Technology",
  "Computer Applications Technology",
  "Consumer Studies",
  "Dance Studies",
  "Design",
  "Dramatic Arts",
  "Economics",
  "Electrical Technology",
  "Engineering Graphics & Design",
  "English FAL",
  "English HL",
  "Geography",
  "History",
  "Hospitality Studies",
  "Information Technology",
  "Life Orientation",
  "Life Sciences",
  "Mathematical Literacy",
  "Mathematics",
  "Mechanical Technology",
  "Music",
  "Ndebele HL",
  "Northern Sotho HL",
  "Physical Science",
  "Religion Studies",
  "Southern Sotho HL",
  "Swazi HL",
  "Technical Mathematics",
  "Tourism",
  "Tsonga HL",
  "Tswana HL",
  "Venda HL",
  "Visual Arts",
  "Xhosa HL",
  "iSiZulu HL",
];